### ISSUE TITLE
equal high for column... howTo?

### ISSUE THREAD

**Issue by svnt** [alecrios/core#2]
Is it possible to give columns the same/equal hight?

something like in gridlex (http://gridlex.devlint.fr)? (the vertical align top/center/bottom feature there is also neat)

anyway, nice little framework. <3 it!

**Comment by alecrios** [comment]
@svnt thanks! There's no great way to handle this problem in a float-based grid like this one, and it is one of the biggest drawbacks. The next version of core.css grid will probably use flexbox instead of floats, so equal column heights and vertical alignment will be a piece of cake.

For now if you need columns of equal height you would have to do something custom for that component. Let's say it's a row with two columns, you could do something as simple as:

```css
.row {
	display: flex;
	flex-flow: row wrap;
}

.col {
	flex: 0 0 50%;
	max-width: 50%;
}
```

And that will give you equal-height columns.
